### PR TITLE
disable parsing inside code blocks.

### LINKED ISSUE #13: Code in docstring does not parse properly
# Code
In the following demonstration I have tried parsing a simple docstring.
```python
from mydocstring.parse import GoogleDocString

s = """
Hello

Examples:
    ```python
    a = {
        'a': 1,
        'b': 1,
        'c': 1,
    }
    ```
"""

parser = GoogleDocString(s)
p = parser.parse()

for section in p:
    for k,v in section.items():
        print(f'{k}=>{v}')
```
# Output
```
header=>
text=>
Hello

args=>[]
header=>Examples
text=>\```python
a = {
}
\```

args=>[{'field': '', 'signature': '', 'description': "1,\n    'b': 1,\n    'c': 1,"}]
```

Here as you can see the dictionary in the code is being parsed as arguments. This will break the rendering as well. Do we have a workaround for this? :smile:

### PR DESCRIPTION
**Pull request by ooreilly**
Resolves #13 

@ariG23498 please give this PR a try and see if it works for you. 

I realized that there's probably one more type of code block that can break things. You can also write code as 
```
"""
>>> a = {'a' : 1 } 

"""
```
We can resolve that in a future PR if needed. For now, let's see if there are any problems with the current fix. Thanks!

### CODE REVIEW

**Comment by ariG23498** [comment]
Hey @ooreilly Thanks for the quick iteration.

I have come across some problems here. I have created a file named `test_check.py` in the root directory and am trying to get the output of the code.
## Directory Structure
```bash
.
├── CONTRIBUTING.md
├── CONTRIBUTORS.md
├── examples
│   ├── ...
│   └── README.md
├── examples.sh
├── LICENSE
├── MANIFEST.in
├── mydocstring
│   ├── ...
│   └── parse.py
├── README.md
├── setup.py
├── test_check.py ## The file that I created
└── tutorials
    └── begin.ipynb

```
## test_check.py
```python
from mydocstring.parse import GoogleDocString

s = """
Hello

Examples:
    ```python
    a = {
        'a': 1,
        'b': 1,
        'c': 1,
    }
    ```
"""

parser = GoogleDocString(s)
p = parser.parse()

for section in p:
    for k,v in section.items():
        print(f'{k}=>{v}')
```

## Ouput
```bash
Traceback (most recent call last):
  File "test_check.py", line 17, in <module>
    p = parser.parse()
  File "/home/aritra/Documents/Checking/mydocstring/mydocstring/parse.py", line 138, in parse
    self.data.append(self.parse_section(section))
  File "/home/aritra/Documents/Checking/mydocstring/mydocstring/parse.py", line 365, in parse_section
    self._parsing[linenum] += len(code)
KeyError: 1
```

Am I missing out on somethig, here?

**Comment by ooreilly** [comment]
@ariG23498 sorry about that! Try now. It should be `self._parsing['linenum'] += len(code)`. I don't understand why the tests didn't crash due to this mistake.

**Comment by ariG23498** [comment]
@ooreilly The fix works like a charm :rose: 
Thanks for the quick fix
Can we expect a bump in the version so that we can upgrade the pip package and imbibe the changes?

**Comment by ooreilly** [comment]
@ariG23498 I'm glad to hear that it is working now. I just had to fix the test.

Yes, I'm going to bump the version and deploy it next.

**Comment by ooreilly** [comment]
@ariG23498 latest version should install via pip now. Thanks again for all your help with improving the package.

**Pull request merged**
